* Python presentations & slides
** What is this repository?
This is a repository that contains python lectures, slides & exercises for my Python basics course modules. You may either view them using [[http://jupyter.org/][Jupyter Notebook]] or by simply opening the corresponding slides.html within each folder. It's purpose is to guide a lecture on the basics of Python and provide context & examples.

** Where's the solutions to the exercises?
They will be in a separate repository and made available after this repository is more or less complete.

** May I use this repository?
You are 100% free to use, fork, change and reproduce this content. All I ask for is the occassional plug.

If you want to use these slides with all of their interactive glory in Jupyter Notebook, you will need to use the [[https://github.com/damianavila/RISE][RISE]] extension. Both Jupyter Nodebook and RISE can be installed by following directions for various Linux distros or your other OS of choice (Mac/Windows).

** May I contribute to this repository?
You may, though, keep in mind that I have a set order for these course modules. I will need to merge changes at my discretion.

** What's included
Also note this repository is a _work in progress_. I am building and refining it as I go. Check back or perform a `git pull` periodically to get updates.

*** TODO Lectures & Slides [22%]
   - [ ] How to get the most out these modules
   - [X] [[./introduction][What is Python]]?
   - [ ] Data Types & Variables
   - [ ] Iterables (lists, dictionaries, tuples, iterating, slicing, built ins)
   - [ ] Control Flow (looping, operators, try/exception blocks)
   - [X] [[./functions][Functions]] (basics, lambdas, closures, decorators)
   - [ ] The Standard Library [0/2]
     - [ ] What's in the Library (where to learn more)
     - [ ] File Management (os/shutil) - The standard library by example
   - [ ] Object Oriented Python (classes, constructors, methods, inheritance)
   - [ ] Package Management (using pip, using packages, writing your own)
